BEGIN TRANSACTION;
ALTER TABLE datas ADD COLUMN setcode2 INTEGER DEFAULT 0;
ALTER TABLE datas ADD COLUMN setcode3 INTEGER DEFAULT 0;
ALTER TABLE datas ADD COLUMN setcode4 INTEGER DEFAULT 0;
UPDATE datas SET setcode2 = 0x13a WHERE id IN (8512558, 55088578);
COMMIT;
